In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
import numpy as np

X = np.arange(1, 101, step=0.1)
y = [x + 10 for x in X]

X = tf.cast(tf.constant(X), dtype=tf.float32)
y = tf.cast(tf.constant(y), dtype=tf.float32)

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-02-07 22:06:15.879977: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-02-07 22:06:15.880236: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_shape=(1,), activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(
    loss=tf.keras.losses.mean_absolute_error,
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
    metrics=['mean_absolute_error']
)

model.fit(X, y, epochs=100)

2022-02-07 22:06:43.191573: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Epoch 1/100


2022-02-07 22:06:43.439562: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


32/32 [==============================] - 2s 15ms/step - loss: 19.9525 - mean_absolute_error: 19.9525
Epoch 2/100
32/32 [==============================] - 0s 5ms/step - loss: 10.6417 - mean_absolute_error: 10.6417
Epoch 3/100
32/32 [==============================] - 0s 5ms/step - loss: 6.1269 - mean_absolute_error: 6.1269
Epoch 4/100
32/32 [==============================] - 0s 5ms/step - loss: 5.8585 - mean_absolute_error: 5.8585
Epoch 5/100
32/32 [==============================] - 0s 5ms/step - loss: 11.0244 - mean_absolute_error: 11.0244
Epoch 6/100
32/32 [==============================] - 0s 5ms/step - loss: 6.0319 - mean_absolute_error: 6.0319
Epoch 7/100
32/32 [==============================] - 0s 4ms/step - loss: 5.5507 - mean_absolute_error: 5.5507
Epoch 8/100
32/32 [==============================] - 0s 5ms/step - loss: 6.0971 - mean_absolute_error: 6.0971
Epoch 9/100
32/32 [==============================] - 0s 5ms/step - loss: 3.9051 - mean_absolute_error: 3.9051
Epoch 10/100
32

In [5]:
model.predict([10, 20, 30])


2022-02-07 22:07:34.692503: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


array([[20.53152 ],
       [31.073574],
       [41.589252]], dtype=float32)

In [11]:
import numpy
import scipy
import pandas
import category_encoders
import GPy
import imblearn
import ipywidgets
import jupyterlab
import fancyimpute
import matplotlib
import mlxtend
import openml
import pods
import sklearn
import seaborn

In [13]:
print(numpy.__version__)
print(scipy.__version__)
print(pandas.__version__)
print(category_encoders.__version__)
print(GPy.__version__)
print(imblearn.__version__)
print(ipywidgets.__version__)
print(jupyterlab.__version__)
print(fancyimpute.__version__)
print(matplotlib.__version__)
print(mlxtend.__version__)
print(openml.__version__)
# print(pods.__version__)
print(sklearn.__version__)
print(seaborn.__version__)


1.21.5
1.8.0
1.4.0
2.3.0
1.10.0
0.9.0
7.6.5
3.2.9
0.7.0
3.5.1
0.19.0
0.12.2
1.0.2
0.11.2


In [97]:
a = np.arange(10)**2
print(a)
a[::-1]

[ 0  1  4  9 16 25 36 49 64 81]


array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [1]:
%matplotlib inline 
import openml as oml 
import numpy as np 
import matplotlib.pyplot as plt 
import sklearn

from packaging import version 
import sklearn 
import tensorflow

sklearn_version = sklearn.__version__
tensorflow_version = tensorflow.__version__

if version.parse(tensorflow_version) < version.parse("2.2.0"):
    print("Tensorflow is outdated. This is version {}. Please update to 2.2 or later (e.g. 2.4)".format(tensorflow_version))
elif version.parse(tensorflow_version) < version.parse("2.4.0"):
    print("Tensorflow version is <2.4. This will likely work but we recommend updating to 2.4".format(tensorflow_version))
else:
    print("Looks good. You may continue :)")


Looks good. You may continue :)
